### ISSUE TITLE
Not working project on Replit

### ISSUE THREAD

**Issue by Razboinicul** [replit/play#33]
This is what it shows:
pygame 2.1.2 (SDL 2.0.16, Python 3.8.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import play # this is the first line in the program
  File "/home/runner/Platformer-Play/venv/lib/python3.8/site-packages/play/__init__.py", line 3, in <module>
    from .play import *
  File "/home/runner/Platformer-Play/venv/lib/python3.8/site-packages/play/play.py", line 88, in <module>
    _pygame_display = pygame.display.set_mode((screen.width, screen.height), pygame.DOUBLEBUF)
pygame.error: No available video device

Also this is the project: https://replit.com/@R9Gaming/Platformer-Play#main.py

**Comment by Razboinicul** [comment]
Sorry.
