### ISSUE TITLE
error on ctrl-q

### ISSUE THREAD

**Issue by aoloe** [replit/play#8]
sometimes i get the following error... i only notice it when i'm trying to quit, but i'm not 100% sure yet that it is related to quitting, nor did i find a way to reproduce it.

```
Exception in callback _game_loop() at /home/ale/src/dojo-resources/cards-python/play/venv/lib/python3.7/site-packages/play/play.py:807
handle: <Handle _game_loop() at /home/ale/src/dojo-resources/cards-python/play/venv/lib/python3.7/site-packages/play/play.py:807>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ale/src/dojo-resources/cards-python/play/venv/lib/python3.7/site-packages/play/play.py", line 834, in _game_loop
    _keys_released_this_frame.append(_pressed_keys[event.key])
KeyError: 311
```

**Comment by aoloe** [comment]
i'm getting the error from time to time, and i'm now tending to thing that it relates to key presses in general... but i normally don't press many other keys  than ctrl-q...

**Comment by aoloe** [comment]
oh, yes : - )
it can be the reason for the error...
